### ISSUE TITLE
Navigation with two charts

### ISSUE THREAD

**Issue by mashinista** [Jeff-Tian/jquery.flot.navigationControl#2]
Hi, nice plugin. I have a question and looking for some help. I have two or more flot charts displayed on the same page using different data for each. Is it possible to zoom, drag or apply any action on one graph and have other graphs follow that same navigation action. For example, if I drag first chart to the right, I would like other graphs to move exactly as the one on which action was applied. Thanks

**Comment by Jeff-Tian** [comment]
Good idea! Will do it after I have done another project at hand.

**Comment by Jeff-Tian** [comment]
Thank you very much for reporting it! Fixed now, you can check this online example: http://zizhujy.com/JsLibs/NavigationControl?example=MultipleCharts
