### ISSUE TITLE
User configured options are ignored

### ISSUE THREAD

**Issue by JamesJ-Yuan** [Jeff-Tian/jquery.flot.navigationControl#3]
I've been trying this plugin out and it works pretty well except that the homeRange option does not work. It always uses the default homeRange. I believe the issue is that in your zoomHome option you use the options variable you define instead of retrieving the user configured options through plot.getOptions()

I'm not very familiar with Javascript or the inner working of flot chart but by adding the line:
var options = plot.getOptions()
in the zoomHome function I was able to get it working properly.

I believe that the user options are also ignored in the other zoom functions.

**Comment by Jeff-Tian** [comment]
You are right, rolled your change in. Thank you very much!!
