### ISSUE TITLE
EDITED

### ISSUE THREAD

**Issue by ghost** [Jeff-Tian/jquery.flot.navigationControl#4]
EDITED

**Comment by Jeff-Tian** [comment]
I think this is a good suggestion, will add it.

**Comment by Jeff-Tian** [comment]
Will add the functionality described by the original issue:

> [jquery.flot.navigationControl] Vertical zoom only (#4)‏
> 
> Actions  
> Darkkz   7/29/2014   Keep this message at the top of your inbox  Groups
> To: Jeff-Tian/jquery.flot.navigationControl
> notifications@github.com
> Hello, is it possible to apply zoom only to the vertical axis?
> When you have data in really different value ranges it's hard to see some of them without zoom, but > applying the zoom makes it lose the global perspective of the x-axes.
> It would be amazing to have some option for allowing the user to zoom only the y-axis.
> 
> ![Screenshot](https://cloud.githubusercontent.com/assets/494123/3733899/cc023592-170d-11e4-970f-fc6f395cc363.png)
> 
> Thank you for this great plugin.

**Comment by Jeff-Tian** [comment]
This is a very good suggestion! Now added this feature, online example: http://zizhujy.com/JsLibs/NavigationControl?example=BasicExample

**Comment by ghost** [comment]
Ok, thanks for it. I thought it had to be changed from Flot, that's why I edited the Issue.
